import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";

// weight: "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | ("100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900")[]; style?: "normal" | "italic" | ("normal" | "italic")[] | undefined; ... 5 more ...; subsets?: ("latin" | ... 2 more ... | "vietnamese")[] | undefined; }'.
//   Property 'weight' is missing in type '{ subsets: "latin"[]; }' but required in type '{ weight: "100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900" | ("100" | "200" | "300" | "400" | "500" | "600" | "700" | "800" | "900")[]; style?: "normal" | "italic" | ("normal" | "italic")[] | undefined; ... 5 more ...; subsets?: ("latin" | ... 2 more ... | "vietnamese")[] | undefined;

const inter = Kanit({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  subsets: ["vietnamese", "latin"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
